name: funcx-dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - xtb-python=22.1
  - pip:
      - ase==3.22.1
      - diaspora-event-sdk==0.1.2
      - kafka-python==1.4.7
      - numpy==1.25.2
      - pillow==10.0.0
      - python-igraph==0.10.8
      - rdkit==2023.9.3
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - squiggle==0.3.1
      - globus-compute-endpoint @ git+https://github.com/AK2000/green-faas-endpoint@power_monitoring_new#subdirectory=compute_endpoint
      - -e git+https://github.com/AK2000/molecular-design-parsl-demo.git#egg=chemfunctions